name: newapp
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.3.3 <4.0.0'


  #---------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

    #UTILITY PACKAGE
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^2.7.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0


    #ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6


  #STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.1.1


  #PRODUCT SPECIFIC
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1



  #FIREBASE
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.1.3
  cached_network_image: ^3.4.0


  #-------------------- ./ PACKAGES END -------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  #------------ LOCAL ASSETS ---------------#

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/products/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
  #------------ LOCAL FONTS ----------------#

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Light.ttf
            weight: 300
          - asset: assets/fonts/Poppins-Regular.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Italic.ttf
            style: italic
          - asset: assets/fonts/Poppins-Medium.ttf
            weight: 500
          - asset: assets/fonts/Poppins-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 800


flutter_launcher_icons:
android: true
ios: true
image_path: assets/logos/logo_oscuro.png # Ruta del icono
